In [1]:
import pandas as pd
import numpy as np
# https://github.com/TirendazAcademy/PANDAS-TUTORIAL/blob/main/01-What-is-Pandas.ipynb

In [2]:
# select → filter → clean → transform → aggregate → reshape

In [3]:
# Series
data = [1, 2, 3, 4, 5]
converted_series = pd.Series(data)
converted_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Creating a DataFrame
df = pd.DataFrame([[1,2,3], [4,5,6], [7.8,9]])
print("Without Labels :\n", df)

# Also we can provide labels for these data
df_with_labels = pd.DataFrame([[1,2,3], [4,5,6], [7.8,9]], columns=['Col1', 'Col2', 'Col3'], index=['Row1', 'Row2', 'Row3'])
print("With Labels :\n", df_with_labels)

Without Labels :
      0  1    2
0  1.0  2  3.0
1  4.0  5  6.0
2  7.8  9  NaN
With Labels :
       Col1  Col2  Col3
Row1   1.0     2   3.0
Row2   4.0     5   6.0
Row3   7.8     9   NaN

In [5]:
"""In most real-world datasets, they are generally stored in files like CSV, Excel, etc.
Mostly larger datasets in Parquet (Columnar format) and Feather (Binary Columnar data) 

These files are optimized for faster reading and writing operations.
if csv takes 1GB of space, parquet will take around 100-200 MB of space only. xls files are generally larger in csv.
"""

'In most real-world datasets, they are generally stored in files like CSV, Excel, etc.\nMostly larger datasets in Parquet (Columnar format) and Feather (Binary Columnar data) \n\nThese files are optimized for faster reading and writing operations.\nif csv takes 1GB of space, parquet will take around 100-200 MB of space only. xls files are generally larger in csv.\n'

In [6]:
dataset_path = r"C:\Users\Sumit Amit\OneDrive\Desktop\ML_Notebook\dataset\obesity_dataset.csv"
dataset = pd.read_csv(dataset_path)

In [7]:
total_rows, total_columns = dataset.shape
print(f"Total Rows: {total_rows} \nTotal Columns: {total_columns}")

Total Rows: 2111
Total Columns: 17

In [8]:
# To see the first 5 roews of the dataset
dataset.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [9]:
# To see the last 5 rows of the dataset
dataset.tail()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [10]:
dataset.sample(5)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
500,26.000000,Female,1.622397,110.792630,Sometimes,yes,3.000000,3.0,no,no,2.704507,yes,0.000000,0.294990,Sometimes,Public_Transportation,Obesity_Type_III
1072,19.443639,Male,1.744733,87.279890,Sometimes,yes,2.442536,3.0,no,no,2.825629,yes,3.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
460,18.000000,Female,1.620000,55.000000,no,yes,2.000000,3.0,no,no,1.000000,yes,1.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
530,19.724106,Female,1.734832,50.000000,Sometimes,no,1.123939,4.0,no,no,1.000000,no,1.303976,0.371941,Frequently,Public_Transportation,Insufficient_Weight
1697,23.327836,Male,1.754439,119.441207,Sometimes,yes,1.893428,3.0,no,no,2.000000,yes,1.917383,0.936480,Sometimes,Public_Transportation,Obesity_Type_II

In [11]:
# When pass random_state, it will always return the same sample every time you run it.
dataset.sample(5, random_state=42)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
544,20.406871,Female,1.755978,53.699561,no,yes,2.0,3.891994,no,no,1.863930,yes,2.870127,2.000000,Frequently,Public_Transportation,Insufficient_Weight
1987,26.000000,Female,1.624950,111.004920,Sometimes,yes,3.0,3.000000,no,no,2.704315,yes,0.000000,0.322666,Sometimes,Public_Transportation,Obesity_Type_III
420,18.000000,Male,1.850000,60.000000,Sometimes,yes,3.0,4.000000,yes,no,2.000000,yes,2.000000,0.000000,Sometimes,Automobile,Insufficient_Weight
527,21.000000,Female,1.520000,42.000000,Sometimes,yes,3.0,1.000000,no,no,1.000000,no,0.000000,0.000000,Frequently,Public_Transportation,Insufficient_Weight
196,22.000000,Male,1.750000,74.000000,Sometimes,no,2.0,3.000000,no,no,2.000000,yes,1.000000,2.000000,Sometimes,Bike,Normal_Weight

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              2111 non-null   float64
 1    Gender                          2111 non-null   object
 2    Height                          2111 non-null   float64
 3    Weight                          2111 non-null   float64
 4    CALC                            2111 non-null   object
 5    FAVC                            2111 non-null   object
 6    FCVC                            2111 non-null   float64
 7    NCP                             2111 non-null   float64
 8    SCC                             2111 non-null   object
 9    SMOKE                           2111 non-null   object
 10   CH2O                            2111 non-null   float64
 11   family_history_with_overweight  2111 non-null   object
 12   FAF                             2111 non-null   float64
 13   TUE                             2111 non-null   float64
 14   CAEC                            2111 non-null   object
 15   MTRANS                          2111 non-null   object
 16   NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [13]:
dataset.columns

# Show in list format
# list(dataset.columns)
# dataset.columns.tolist()

Index(['Age      ', ' Gender', ' Height  ', ' Weight    ', ' CALC      ',
       ' FAVC', ' FCVC    ', ' NCP     ', ' SCC', ' SMOKE', ' CH2O    ',
       ' family_history_with_overweight', ' FAF     ', ' TUE     ',
       ' CAEC      ', ' MTRANS               ', ' NObeyesdad'],
      dtype='object')

In [14]:
# Remove all spaces around column names
dataset.columns = dataset.columns.str.strip()
dataset.columns

Index(['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP',
       'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE',
       'CAEC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [15]:
# Size -> Total number of elements in the DataFrame.
dataset.size

35887

In [16]:
# Statistical Summary
dataset.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [17]:
# Accessing data
dataset.loc[0, 'Age'] # Accessing Age of first row using label-based indexing

np.float64(21.0)

In [18]:
# Group of rows and columns
dataset.loc[0:4, 'Age']  # Accessing Age of first 5 rows
dataset.loc[0:4, ['Age', 'Weight']]  # Accessing Age and Weight of first 5 rows

    Age  Weight
0  21.0    64.0
1  21.0    56.0
2  23.0    77.0
3  27.0    87.0
4  22.0    89.8

In [19]:
# Range of rows and all columns
"""Means from row index 0 to 4 (inclusive) and all columns from 'Age' to 'FAVC' (inclusive)."""
dataset.loc[0:4, "Age":"FAVC"]

    Age   Gender  Height  Weight         CALC   FAVC
0  21.0   Female    1.62    64.0   no           no
1  21.0   Female    1.52    56.0   Sometimes    no
2  23.0   Male      1.80    77.0   Frequently   no
3  27.0   Male      1.80    87.0   Frequently   no
4  22.0   Male      1.78    89.8   Sometimes    no

In [20]:
# To see all rows from a specific column range
dataset.loc[:, 'Age':'FAVC']

            Age   Gender    Height      Weight         CALC   FAVC
0     21.000000   Female  1.620000   64.000000   no           no
1     21.000000   Female  1.520000   56.000000   Sometimes    no
2     23.000000   Male    1.800000   77.000000   Frequently   no
3     27.000000   Male    1.800000   87.000000   Frequently   no
4     22.000000   Male    1.780000   89.800000   Sometimes    no
...         ...      ...       ...         ...          ...    ...
2106  20.976842   Female  1.710730  131.408528   Sometimes    yes
2107  21.982942   Female  1.748584  133.742943   Sometimes    yes
2108  22.524036   Female  1.752206  133.689352   Sometimes    yes
2109  24.361936   Female  1.739450  133.346641   Sometimes    yes
2110  23.664709   Female  1.738836  133.472641   Sometimes    yes

[2111 rows x 6 columns]

In [21]:
# To see the specific rows and specific columns
dataset.loc[50:70, 'Age':'FAVC']

     Age   Gender  Height  Weight         CALC   FAVC
50  21.0   Female    1.61    54.5   Sometimes    yes
51  20.0   Female    1.50    44.0   Sometimes    yes
52  23.0   Female    1.64    52.0   no           yes
53  23.0   Female    1.63    55.0   no           no
54  22.0   Female    1.60    55.0   no           no
55  23.0   Male      1.68    62.0   Sometimes    no
56  22.0   Male      1.70    70.0   Sometimes    yes
57  21.0   Male      1.64    65.0   no           no
58  17.0   Female    1.65    67.0   no           yes
59  20.0   Male      1.76    55.0   no           yes
60  21.0   Female    1.55    49.0   Sometimes    yes
61  20.0   Male      1.65    58.0   Sometimes    yes
62  22.0   Male      1.67    62.0   Sometimes    yes
63  22.0   Male      1.68    55.0   Sometimes    yes
64  21.0   Female    1.66    57.0   no           yes
65  21.0   Female    1.62    69.0   no           yes
66  23.0   Male      1.80    90.0   Frequently   yes
67  23.0   Male      1.65    95.0   Frequently   yes
68  30.0   Male      1.76   112.0   Frequently   yes
69  23.0   Male      1.80    60.0   Sometimes    no
70  23.0   Female    1.65    80.0   no           yes

In [22]:
# in iloc we use integer-based indexing
# dataset.iloc[row_range, column_range]
dataset.iloc[0:10, 0:5]

    Age   Gender  Height  Weight         CALC
0  21.0   Female    1.62    64.0   no
1  21.0   Female    1.52    56.0   Sometimes
2  23.0   Male      1.80    77.0   Frequently
3  27.0   Male      1.80    87.0   Frequently
4  22.0   Male      1.78    89.8   Sometimes
5  29.0   Male      1.62    53.0   Sometimes
6  23.0   Female    1.50    55.0   Sometimes
7  22.0   Male      1.64    53.0   Sometimes
8  24.0   Male      1.78    64.0   Frequently
9  22.0   Male      1.72    68.0   no

In [ ]:
# If we want to single value access for that we use at and iat. Slicing is not allowed here.
# at and iat expects both row and column labels/indices to be provided as single values.
# dataset.at[row_label, column_label]
dataset.at[0, "Age"]

np.float64(21.0)

In [25]:
dataset.iat[0, 5]

' no  '

In [ ]:
dataset.iat[0, 1]

' Female'

In [34]:
dataset["Age"]

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [35]:
# You can access also multiple columns
dataset[["Age", "Weight"]]

            Age      Weight
0     21.000000   64.000000
1     21.000000   56.000000
2     23.000000   77.000000
3     27.000000   87.000000
4     22.000000   89.800000
...         ...         ...
2106  20.976842  131.408528
2107  21.982942  133.742943
2108  22.524036  133.689352
2109  24.361936  133.346641
2110  23.664709  133.472641

[2111 rows x 2 columns]